from pydantic import BaseModel, Field
from typing import Literal, Union, List, Dict, Any, Optional


class MessageResponse(BaseModel):
    """Generic message response model for root and informational endpoints."""
    message: str = Field(
        ...,
        description="Welcome or informational status message",
        examples=["Welcome to AI Summarizer API"]
    )


class HealthResponse(BaseModel):
    """Health check heartbeat response model."""
    status: str = Field(
        ...,
        description="Operational status of the backend service",
        examples=["Running"]
    )


class ErrorResponse(BaseModel):
    """Standardized error payload returned for HTTP 400, 413, 422, and 500 responses."""
    detail: Union[str, List[Dict[str, Any]]] = Field(
        ...,
        description="Detailed explanation of the error or validation failure list",
        examples=["Unsupported file format '.exe'. Supported formats are TXT, PDF, and DOCX."]
    )


class SummaryRequest(BaseModel):
    """Request model for direct text summarization."""
    text: str = Field(
        ...,
        description="Raw input text content to summarize",
        examples=["Artificial intelligence has seen rapid advancements in natural language processing..."]
    )
    length: Literal["short", "medium", "long"] = Field(
        default="medium",
        description="Desired length of the generated summary: short (concise), medium (balanced), long (comprehensive)",
        examples=["medium"]
    )
    format: Literal["paragraph", "bullets", "table"] = Field(
        default="paragraph",
        description="Output presentation format: paragraph (narrative), bullets (bullet points), table (markdown table)",
        examples=["paragraph"]
    )
    executive: bool = Field(
        default=False,
        description="When enabled, produces a strategic high-level briefing tailored for leadership",
        examples=[False]
    )


class SummaryResponse(BaseModel):
    """Response model containing synthesized summary text."""
    summary: str = Field(
        ...,
        description="Synthesized summary output generated by Groq LLM",
        examples=["This document outlines the core architectural patterns of modern cloud services..."]
    )


class KeyPointsResponse(BaseModel):
    """Response model containing extracted salient takeaways."""
    key_points: list[str] = Field(
        ...,
        description="Extracted list of salient key takeaways, numbered or bulleted",
        examples=[[
            "Natural language models have evolved from rule-based engines to generative transformers.",
            "FastAPI provides sub-millisecond asynchronous request routing with native OpenAPI generation.",
            "Faster-whisper enables high-throughput offline speech transcription with INT8 quantization."
        ]]
    )


class SectionSummary(BaseModel):
    """Summary of an individual chunk/section produced during the hierarchical Map phase."""
    section_index: int = Field(
        ...,
        description="Zero-based sequential index of the document chunk",
        examples=[0]
    )
    summary: str = Field(
        ...,
        description="Concise synthesis of this specific section",
        examples=["Section 1 introduces the system requirements and hardware specifications."]
    )
    importance_score: Optional[float] = Field(
        default=None,
        description="Hybrid importance score between 0.0 and 1.0",
        examples=[0.87]
    )
    importance_reason: Optional[str] = Field(
        default=None,
        description="Reasoning explaining the importance assessment",
        examples=["High importance: contains key findings, numerical metrics, and decisions."]
    )
    importance_signals: Optional[Dict[str, bool]] = Field(
        default=None,
        description="Detected informational signals in this section",
        examples=[{"key_findings": True, "decisions": False, "metrics": True, "actions": True, "risks": False, "conclusion": True}]
    )
    is_redundant: Optional[bool] = Field(
        default=False,
        description="Whether this section was flagged as redundant with another section",
        examples=[False]
    )
    redundancy_info: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Details regarding redundancy type, similarity score, and which section was retained",
        examples=[{"is_redundant": True, "redundancy_type": "near_duplicate", "similarity": 0.91, "kept_section": 1, "removed_section": 2, "reason": "Section 2 repeats Section 1."}]
    )


class HierarchicalSummaryResponse(BaseModel):
    """Response model for Map-Reduce hierarchical document summarization."""
    final_summary: str = Field(
        ...,
        description="Master synthesized summary produced by aggregating all section summaries during the Reduce phase",
        examples=["Comprehensive synthesis covering all sections of the document with overarching conclusions."]
    )
    section_summaries: list[SectionSummary] = Field(
        ...,
        description="List of individual chunk summaries generated during the Map phase"
    )
    total_sections: int = Field(
        ...,
        description="Total number of chunks partitioned and summarized",
        examples=[3]
    )
    redundant_sections_count: Optional[int] = Field(
        default=0,
        description="Number of redundant sections identified and suppressed from final synthesis",
        examples=[1]
    )
    faithfulness: Optional["FaithfulnessResult"] = Field(
        default=None,
        description="Faithfulness verification details assessing whether the final summary is grounded in the source document"
    )


class FaithfulnessClaim(BaseModel):
    """Individual factual claim extracted from a summary with verification evidence."""
    claim: str = Field(
        ...,
        description="Text of the extracted factual claim",
        examples=["Revenue increased by 25% to $4.2 million."]
    )
    status: Literal["SUPPORTED", "PARTIALLY_SUPPORTED", "UNSUPPORTED", "UNCERTAIN"] = Field(
        ...,
        description="Verification status indicating evidence grounding in the source document",
        examples=["SUPPORTED"]
    )
    evidence: Optional[str] = Field(
        default=None,
        description="Source document passage supporting or addressing the claim",
        examples=["Quarterly revenue increased 25% year-over-year to $4.2 million in Q4."]
    )
    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Confidence score of the verification result between 0.0 and 1.0",
        examples=[0.98]
    )
    claim_type: Optional[str] = Field(
        default=None,
        description="Class of claim: quantitative, date_specific, entity_statement, or factual",
        examples=["quantitative"]
    )
    reason: Optional[str] = Field(
        default=None,
        description="Explanation detailing why the claim was classified with this status",
        examples=["Directly supported by matching source passage."]
    )


class FaithfulnessResult(BaseModel):
    """Overall faithfulness evaluation metrics and individual claim verification records."""
    faithfulness_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Aggregated faithfulness score between 0.0 and 1.0",
        examples=[0.92]
    )
    status: Literal["HIGH", "MODERATE", "LOW"] = Field(
        ...,
        description="Categorical faithfulness status: HIGH (>=0.80), MODERATE (0.50-0.79), LOW (<0.50)",
        examples=["HIGH"]
    )
    claims_checked: int = Field(
        ...,
        ge=0,
        description="Total number of factual claims extracted and checked",
        examples=[5]
    )
    supported_claims: int = Field(
        ...,
        ge=0,
        description="Count of fully supported claims",
        examples=[4]
    )
    partially_supported_claims: int = Field(
        ...,
        ge=0,
        description="Count of partially supported claims",
        examples=[1]
    )
    unsupported_claims: int = Field(
        ...,
        ge=0,
        description="Count of unsupported or inconsistent claims",
        examples=[0]
    )
    uncertain_claims: Optional[int] = Field(
        default=0,
        ge=0,
        description="Count of ambiguous or uncertain claims that could not be confidently verified",
        examples=[0]
    )
    claims: list[FaithfulnessClaim] = Field(
        default_factory=list,
        description="List of individual claim verification records"
    )
