from pydantic import BaseModel, Field
from typing import Literal, Union, List, Dict, Any


class MessageResponse(BaseModel):
    """Generic message response model for root and informational endpoints."""
    message: str = Field(
        ...,
        description="Welcome or informational status message",
        examples=["Welcome to AI Summarizer API"]
    )


class HealthResponse(BaseModel):
    """Health check heartbeat response model."""
    status: str = Field(
        ...,
        description="Operational status of the backend service",
        examples=["Running"]
    )


class ErrorResponse(BaseModel):
    """Standardized error payload returned for HTTP 400, 413, 422, and 500 responses."""
    detail: Union[str, List[Dict[str, Any]]] = Field(
        ...,
        description="Detailed explanation of the error or validation failure list",
        examples=["Unsupported file format '.exe'. Supported formats are TXT, PDF, and DOCX."]
    )


class SummaryRequest(BaseModel):
    """Request model for direct text summarization."""
    text: str = Field(
        ...,
        description="Raw input text content to summarize",
        examples=["Artificial intelligence has seen rapid advancements in natural language processing..."]
    )
    length: Literal["short", "medium", "long"] = Field(
        default="medium",
        description="Desired length of the generated summary: short (concise), medium (balanced), long (comprehensive)",
        examples=["medium"]
    )
    format: Literal["paragraph", "bullets", "table"] = Field(
        default="paragraph",
        description="Output presentation format: paragraph (narrative), bullets (bullet points), table (markdown table)",
        examples=["paragraph"]
    )
    executive: bool = Field(
        default=False,
        description="When enabled, produces a strategic high-level briefing tailored for leadership",
        examples=[False]
    )


class SummaryResponse(BaseModel):
    """Response model containing synthesized summary text."""
    summary: str = Field(
        ...,
        description="Synthesized summary output generated by Groq LLM",
        examples=["This document outlines the core architectural patterns of modern cloud services..."]
    )


class KeyPointsResponse(BaseModel):
    """Response model containing extracted salient takeaways."""
    key_points: list[str] = Field(
        ...,
        description="Extracted list of salient key takeaways, numbered or bulleted",
        examples=[[
            "Natural language models have evolved from rule-based engines to generative transformers.",
            "FastAPI provides sub-millisecond asynchronous request routing with native OpenAPI generation.",
            "Faster-whisper enables high-throughput offline speech transcription with INT8 quantization."
        ]]
    )


class SectionSummary(BaseModel):
    """Summary of an individual chunk/section produced during the hierarchical Map phase."""
    section_index: int = Field(
        ...,
        description="Zero-based sequential index of the document chunk",
        examples=[0]
    )
    summary: str = Field(
        ...,
        description="Concise synthesis of this specific section",
        examples=["Section 1 introduces the system requirements and hardware specifications."]
    )


class HierarchicalSummaryResponse(BaseModel):
    """Response model for Map-Reduce hierarchical document summarization."""
    final_summary: str = Field(
        ...,
        description="Master synthesized summary produced by aggregating all section summaries during the Reduce phase",
        examples=["Comprehensive synthesis covering all sections of the document with overarching conclusions."]
    )
    section_summaries: list[SectionSummary] = Field(
        ...,
        description="List of individual chunk summaries generated during the Map phase"
    )
    total_sections: int = Field(
        ...,
        description="Total number of chunks partitioned and summarized",
        examples=[3]
    )
